algoritmo "Calculo_Idade_Se"

var nasc,ano,idade:Inteiro

inicio

      Escreva("em que ano voçe nasceu???")
      Leia(nasc)
      Escreva("Em que ano estamos????")
      Leia(ano)
      idade <- (ano-nasc)
      Escreval(" Em ",ano," voçe tera ",idade," anos ")
      Se (idade>=21) entao
         Escreval(" em ",ano," e voçe ja atingiu a maior idade")
                             Fimse

      
      
fimalgoritmo
