algoritmo "Media"

var
Numero1, Media, Numero2: Real

inicio

Escreval("      Media       ")
Escreva("Digite o Primeiro Numero: ",Numero1)
Leia(Numero1)
Escreva("Digite o Segundo Numero: ",Numero2)
Leia(Numero2)

Media<- (Numero1 + Numero2) / 2
Escreva ( " A Media Entre " ,Numero1, " e " ,Numero2," Foi " ,Media)

// Dentro de um Escreva se devem ser separadas por  virgula entre as variaveis


fimalgoritmo
