algoritmo "09_Usuario_contando_teste"

var
cont1,cont2,cont3,contador:inteiro
inicio
Escreval("0nde pretende começar")
Leia(cont1)
Escreval("ate onde pretende contar")
Leia(cont2)
Escreval("qual sera o salto")
Leia(cont3)
contador <- cont1
Enquanto (contador <= cont2) faca
   Escreval(cont1)
   contador <- (contador + cont3
FimEnquanto
Escreval ("Voçe terminou de contar")
fimalgoritmo
