algoritmo "Contar"

var
   Numero,Contador,Salto:Inteiro

inicio
      Escreval(" quer contar ate quanto???")
      Leia(Numero)
      Escreval(" quer saltar ate quanto???")
      Leia(Salto)
      Contador <- 0 // Onde vai começar contagem //
      Enquanto (Contador <= Numero)  Faca
      Escreval(Contador)
               Contador <- Contador + Salto
      FimEnquanto

fimalgoritmo
