algoritmo "Velinhas_Creuza"

var  Ano1,Ano2,Idade:  Inteiro
     Nome:Caractere
inicio

Escreval("Digite o seu ano de nascimento",Ano1)
Leia (Ano1)

Escreval("Digite o ano Atual ",Ano2)
Leia (Ano2)

Idade <- Ano2 - Ano1

Escreval ("em",Ano2," Voçe tera " ,Idade, " anos de idade")
Se (Idade >= 21 ) entao

    EscrevaL ("e  ja tera atingido a mior maioridade")
    
FimSe

fimalgoritmo
